
# This file is automatically generated, you probably don't want to edit this

kappaOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "kappaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            weights = "unweighted", ...) {

            super$initialize(
                package='Kappa',
                name='kappa',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep)
            private$..weights <- jmvcore::OptionList$new(
                "weights",
                weights,
                options=list(
                    "unweighted",
                    "squared"),
                default="unweighted")

            self$.addOption(private$..dep)
            self$.addOption(private$..weights)
        }),
    active = list(
        dep = function() private$..dep$value,
        weights = function() private$..weights$value),
    private = list(
        ..dep = NA,
        ..weights = NA)
)

kappaResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        ka = function() private$.items[["ka"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Kappa")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Kappa"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ka",
                title="Cohen's Kappa for 2 Raters",
                rows=1,
                columns=list(
                    list(
                        `name`="weights", 
                        `type`="text"),
                    list(
                        `name`="kappa", 
                        `type`="number"),
                    list(
                        `name`="upper_CI", 
                        `type`="number"),
                    list(
                        `name`="lower_CI", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

kappaBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "kappaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Kappa',
                name = 'kappa',
                version = c(1,0,0),
                options = options,
                results = kappaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Kappa
#'
#' 
#' @param data .
#' @param dep .
#' @param weights .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ka} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ka$asDF}
#'
#' \code{as.data.frame(results$ka)}
#'
#' @export
kappa <- function(
    data,
    dep,
    weights = "unweighted") {

    if ( ! requireNamespace('jmvcore'))
        stop('kappa requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- kappaOptions$new(
        dep = dep,
        weights = weights)

    analysis <- kappaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
